### ISSUE TITLE
Need guidance on cocoapods in mobile steps

### ISSUE THREAD

**Issue by lidderupk** [Call-for-Code/Solution-Starter-Kit-Disasters-2020#10]
One of the steps under `Run the mobile application` asks the user to `Install pod dependencies: pod install.`. It might be helpful to ask them to install cocoapods first or give other guidance.

`https://guides.cocoapods.org/using/getting-started.html#getting-started`

Cocoapods might have it's own dependencies, we should however provide some initial link.

**Comment by vabarbosa** [comment]
@lidderupk thanks.
in the pre-requisites i mention (and link to) installing [React Native CLI dependencies](https://reactnative.dev/docs/getting-started.html) which includes cocoapod, but i'll clarify further.

**Comment by lidderupk** [comment]
👍 

I didn't see cocoapods mentioned on the that page - https://reactnative.dev/docs/getting-started.html

Thanks Va!
