### ISSUE TITLE
Step links in readme do not jump to the right section

### ISSUE THREAD

**Issue by lidderupk** [Call-for-Code/Solution-Starter-Kit-Disasters-2020#8]
The following links do not jump to the right section 

```
Steps

    Set up an instance of Watson Assistant.
    Generate an API Key from the HERE Developer Portal.
    Run the server.
    Run the mobile application.
```

Expected:
`https://github.com/Call-for-Code/Solution-Starter-Kit-Disasters-2020#1-set-up-an-instance-of-watson-assistant`. 

Actual:
`https://github.com/Call-for-Code/Solution-Starter-Kit-Disasters-2020#1.-set-up-an-instance-of-watson-assistant`

**Comment by vabarbosa** [comment]
@lidderupk thanks. updated.
