### ISSUE TITLE
Step to get assistant id and api key seem unclear

### ISSUE THREAD

**Issue by lidderupk** [Call-for-Code/Solution-Starter-Kit-Disasters-2020#9]
Step number 5 below says to grab assistant id and api key from the `dialogs skill's action menu`. 

```
1. Set up an instance of Watson Assistant

Log in to IBM Cloud and provision a Watson Assistant instance.

    1. Provision an instance of Watson Assistant from the IBM Cloud catalog.
    2. Launch the Watson Assistant service.
    3. Create an Assistant.
    4. Add a dialog skill to the Assistant by importing the starter-kit-flood-dialog-skill.json file.
    5. Click the dialog skill's action menu, and select View API Details.
    6. Note the Assistant ID and Api Key.
    7. Go to Preview Link to get a link to test and verify the dialog skill.
```

The assistant id and api key are in the assistant menu and not the skill menu. Perhaps reword as 

> 5. Go back to All Assistants, open Settings from the action menu and click on API Details to get the **Assistant ID** and **Api Key**.

**Comment by vabarbosa** [comment]
@lidderupk thanks.
API details can also be reached from the dialog skill's menu, but i'll go ahead and clarify further


![image](https://user-images.githubusercontent.com/13156555/77020701-041a6300-695b-11ea-9010-bb36f6c7e632.png)

**Comment by lidderupk** [comment]
Ah I see. The ApiKey is there, but I don't see Assistant ID. Maybe I am missing something.

Thanks Va!

**Comment by vabarbosa** [comment]
@lidderupk thanks again. not sure what i was looking at the but the assistant id is not on that particular screen. instruction has been updated!
